# The URL the site will be built for
base_url = "https://tcanabrava.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
feed_limit = 20
theme = "even"

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

title = "Tomaz Canabrava Ramblings"
description = "Somewhat updated list of C++, Qt and KDE bits"

generate_feed = true

[markdown]
highlight_code = true

[extra]
even_title = "Tomaz Canabrava Ramblings"

[languages.en.translations]
language_name = "English"
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
date_format = "%Y-%m-%d"
next_page = "Next Page"
last_page = "Last Page"

